include: package:flutter_lints/flutter.yaml

linters:
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_void_async
    - empty_constructor_bodies
    - void_checks
    - constant_identifier_names

analyzer:
  errors:
    invalid_annotation_target: ignore